import { readFileSync } from "node:fs";
import { join } from "node:path";

export type ChangelogEntry = {
  version: string;
  sections: { kind: string; items: string[] }[];
};

/**
 * Reads the package's own CHANGELOG at build time rather than duplicating
 * release notes here, so the docs can't fall behind a release. The file is
 * generated by changesets, so its shape is stable: `## <version>`, then
 * `### <Major|Minor|Patch> Changes`, then `- ` bullets.
 */
export function getChangelog(): ChangelogEntry[] {
  const path = join(process.cwd(), "..", "..", "packages", "ui", "CHANGELOG.md");
  const raw = readFileSync(path, "utf8");

  const entries: ChangelogEntry[] = [];
  let entry: ChangelogEntry | undefined;
  let section: { kind: string; items: string[] } | undefined;

  for (const line of raw.split("\n")) {
    const version = /^##\s+(?!#)(.+)$/.exec(line);
    if (version) {
      entry = { version: version[1].trim(), sections: [] };
      entries.push(entry);
      section = undefined;
      continue;
    }

    const kind = /^###\s+(.+)$/.exec(line);
    if (kind && entry) {
      section = { kind: kind[1].trim(), items: [] };
      entry.sections.push(section);
      continue;
    }

    const bullet = /^-\s+(.+)$/.exec(line);
    if (bullet && section) {
      // changesets prefixes some bullets with the originating commit hash.
      section.items.push(bullet[1].replace(/^[0-9a-f]{7,}:\s*/, "").trim());
    }
  }

  return entries;
}
